### PR TITLE
add a new function that can get a List of Map structure containing th…

### PR DESCRIPTION
**Pull request by nddipiazza**
…e same thing that the toHTML method has but in a JSON-able format.

### CODE REVIEW

**Comment by ctmay4** [comment]
Sorry to the issues you are having.  We are adding support for SonarQube to our builds.  It seems like that is failing for pull requests coming from forks.  The private access keys are not getting shared. I need to look into possible solutions.

**Comment by nddipiazza** [comment]
No problem! thanks for reaching out!
If it helps, you could give me create branch permissions on the repo and I'll just create my branches there?

**Comment by ctmay4** [comment]
I'm still not sure what to do about SonarQube.  It failed the build but I can see all the unit tests passed.  David, can you please review the PR and we can move this along.

**Comment by angelaszek** [comment]
@ctmay4 This looks fine to me.

**Review by angelaszek — APPROVED** [review]

**Pull request merged**
